<a href="https://colab.research.google.com/github/luizalmin-netizen/trilha-html-modulo-1/blob/main/agente_financeiro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 💰 Orçamento Mensal Modelo em Python

Este modelo básico de orçamento mensal em Python permite que você visualize suas receitas e despesas. Você pode ajustar os valores conforme sua realidade.

---

#### 1. Definição de Receitas Mensais

Começamos listando todas as suas fontes de renda líquida para o mês.

In [1]:
# Defina suas receitas mensais
receitas = {
    'Salário Líquido': 3500.00,  # Exemplo de salário após impostos
    'Renda Extra (Freelance)': 200.00,
    'Outras Receitas': 50.00
}

total_receitas = sum(receitas.values())

print("--- Receitas Mensais ---")
for fonte, valor in receitas.items():
    print(f"{fonte}: R$ {valor:.2f}")
print(f"\nTotal de Receitas: R$ {total_receitas:.2f}")

--- Receitas Mensais ---
Salário Líquido: R$ 3500.00
Renda Extra (Freelance): R$ 200.00
Outras Receitas: R$ 50.00

Total de Receitas: R$ 3750.00

#### 2. Definição de Despesas Fixas

Despesas fixas são aquelas que geralmente não mudam muito de mês para mês e são essenciais para sua vida (aluguel, contas de consumo, etc.).

In [2]:
# Defina suas despesas fixas mensais
despesas_fixas = {
    'Aluguel/Financiamento': 1200.00,
    'Condomínio': 300.00,
    'Luz': 150.00,
    'Água': 80.00,
    'Internet': 100.00,
    'Celular': 60.00,
    'Transporte (Passe Mensal)': 200.00, # Se for fixo
    'Plano de Saúde': 250.00,
    'Academia': 80.00
}

total_despesas_fixas = sum(despesas_fixas.values())

print("\n--- Despesas Fixas ---")
for despesa, valor in despesas_fixas.items():
    print(f"{despesa}: R$ {valor:.2f}")
print(f"\nTotal de Despesas Fixas: R$ {total_despesas_fixas:.2f}")

--- Despesas Fixas ---
Aluguel/Financiamento: R$ 1200.00
Condomínio: R$ 300.00
Luz: R$ 150.00
Água: R$ 80.00
Internet: R$ 100.00
Celular: R$ 60.00
Transporte (Passe Mensal): R$ 200.00
Plano de Saúde: R$ 250.00
Academia: R$ 80.00

Total de Despesas Fixas: R$ 2420.00

#### 3. Definição de Despesas Variáveis

Despesas variáveis são aquelas que flutuam mês a mês e sobre as quais você tem mais controle (alimentação, lazer, compras, etc.).

In [3]:
# Defina suas despesas variáveis mensais (com um valor estimado para o orçamento)
despesas_variaveis = {
    'Alimentação (Mercado)': 600.00,
    'Alimentação (Restaurantes/Delivery)': 300.00,
    'Lazer/Entretenimento': 200.00,
    'Compras (Roupas, Eletrônicos, etc.)': 150.00,
    'Outras Despesas Variáveis': 100.00
}

total_despesas_variaveis = sum(despesas_variaveis.values())

print("\n--- Despesas Variáveis ---")
for despesa, valor in despesas_variaveis.items():
    print(f"{despesa}: R$ {valor:.2f}")
print(f"\nTotal de Despesas Variáveis: R$ {total_despesas_variaveis:.2f}")

--- Despesas Variáveis ---
Alimentação (Mercado): R$ 600.00
Alimentação (Restaurantes/Delivery): R$ 300.00
Lazer/Entretenimento: R$ 200.00
Compras (Roupas, Eletrônicos, etc.): R$ 150.00
Outras Despesas Variáveis: R$ 100.00

Total de Despesas Variáveis: R$ 1350.00

#### 4. Resumo do Orçamento Mensal

Agora vamos calcular o total das despesas e o saldo final do seu orçamento.

In [4]:
total_despesas = total_despesas_fixas + total_despesas_variaveis
saldo_final = total_receitas - total_despesas

print("\n--- Resumo do Orçamento Mensal ---")
print(f"Total de Receitas: R$ {total_receitas:.2f}")
print(f"Total de Despesas Fixas: R$ {total_despesas_fixas:.2f}")
print(f"Total de Despesas Variáveis: R$ {total_despesas_variaveis:.2f}")
print(f"Total Geral de Despesas: R$ {total_despesas:.2f}")

print("-----------------------------------")
if saldo_final > 0:
    print(f"🎉 Saldo Final: R$ {saldo_final:.2f} (Parabéns! Você está com saldo positivo.)")
elif saldo_final < 0:
    print(f"💸 Saldo Final: R$ {saldo_final:.2f} (Atenção! Você está com saldo negativo. Hora de revisar os gastos.)")
else:
    print(f"⚖️ Saldo Final: R$ {saldo_final:.2f} (Seu orçamento está equilibrado.)")

--- Resumo do Orçamento Mensal ---
Total de Receitas: R$ 3750.00
Total de Despesas Fixas: R$ 2420.00
Total de Despesas Variáveis: R$ 1350.00
Total Geral de Despesas: R$ 3770.00
-----------------------------------
💸 Saldo Final: R$ -20.00 (Atenção! Você está com saldo negativo. Hora de revisar os gastos.)

---

### 🚀 Próximos Passos e Recomendações

**Resumo da Situação:** Acabamos de criar um modelo básico para visualizar sua saúde financeira mensal.

**Diagnóstico Financeiro:** O saldo final indica se suas receitas estão cobrindo suas despesas. Um saldo positivo é ideal, enquanto um negativo exige atenção.

**Recomendações Práticas:**
1.  **Personalize:** Edite os valores de `receitas`, `despesas_fixas` e `despesas_variaveis` para refletir sua realidade.
2.  **Acompanhe:** Registre seus gastos reais diariamente/semanalmente para comparar com o orçamento.
3.  **Priorize:** Se o saldo for negativo, analise as despesas variáveis para identificar onde pode cortar ou reduzir.

**Exemplo Aplicado:** Se você notar que o gasto com 'Alimentação (Restaurantes/Delivery)' está muito alto, tente cozinhar mais em casa alguns dias da semana.

**Plano de Ação Passo a Passo:**
1.  **Atualizar valores:** Preencha os dicionários de receitas e despesas com seus números reais.
2.  **Rodar o código:** Execute as células para ver seu saldo atual.
3.  **Analisar:** Observe onde seu dinheiro está indo e identifique possíveis cortes.

**Próximas Ações Recomendadas:**
*   **Meta Financeira Prática para os Próximos 7 Dias:** Monitore ativamente suas despesas variáveis. Tente reduzir 10% do valor que você estimou para 'Lazer/Entretenimento'.
*   **Dica Educativa Adicional:** A regra 50/30/20 é um ótimo guia: 50% da sua renda para necessidades (despesas fixas), 30% para desejos (despesas variáveis e lazer) e 20% para poupança e pagamento de dívidas.

Estou aqui para te ajudar a refinar este orçamento e criar um plano mais detalhado! O que achou? Gostaria de ajustar algum valor ou adicionar mais categorias?

### 📉 Simulação: Redução de 10% nas Despesas Variáveis

Vamos aplicar uma redução de 10% em todas as despesas variáveis para ver como o saldo final do orçamento se comporta. Isso pode te ajudar a identificar o potencial de economia.

In [5]:
# Simulação: Reduzir 10% de cada despesa variável
despesas_variaveis_simuladas = {k: v * 0.90 for k, v in despesas_variaveis.items()}

total_despesas_variaveis_simuladas = sum(despesas_variaveis_simuladas.values())

print("\n--- Despesas Variáveis (com -10% de Redução) ---")
for despesa, valor in despesas_variaveis_simuladas.items():
    print(f"{despesa}: R$ {valor:.2f}")
print(f"\nTotal de Despesas Variáveis Simuladas: R$ {total_despesas_variaveis_simuladas:.2f}")

total_despesas_simuladas = total_despesas_fixas + total_despesas_variaveis_simuladas
saldo_final_simulado = total_receitas - total_despesas_simuladas

print("\n--- Resumo do Orçamento Mensal (com -10% nas Despesas Variáveis) ---")
print(f"Total de Receitas: R$ {total_receitas:.2f}")
print(f"Total de Despesas Fixas: R$ {total_despesas_fixas:.2f}")
print(f"Total de Despesas Variáveis Simuladas: R$ {total_despesas_variaveis_simuladas:.2f}")
print(f"Total Geral de Despesas Simuladas: R$ {total_despesas_simuladas:.2f}")

print("-------------------------------------------------------------------")
if saldo_final_simulado > 0:
    print(f"🎉 Saldo Final Simulado: R$ {saldo_final_simulado:.2f} (Parabéns! Com a redução, você tem saldo positivo.)")
elif saldo_final_simulado < 0:
    print(f"💸 Saldo Final Simulado: R$ {saldo_final_simulado:.2f} (Atenção! Mesmo com a redução, ainda há déficit.)")
else:
    print(f"⚖️ Saldo Final Simulado: R$ {saldo_final_simulado:.2f} (Com a redução, seu orçamento está equilibrado.)")

--- Despesas Variáveis (com -10% de Redução) ---
Alimentação (Mercado): R$ 540.00
Alimentação (Restaurantes/Delivery): R$ 270.00
Lazer/Entretenimento: R$ 180.00
Compras (Roupas, Eletrônicos, etc.): R$ 135.00
Outras Despesas Variáveis: R$ 90.00

Total de Despesas Variáveis Simuladas: R$ 1215.00

--- Resumo do Orçamento Mensal (com -10% nas Despesas Variáveis) ---
Total de Receitas: R$ 3750.00
Total de Despesas Fixas: R$ 2420.00
Total de Despesas Variáveis Simuladas: R$ 1215.00
Total Geral de Despesas Simuladas: R$ 3635.00
-------------------------------------------------------------------
🎉 Saldo Final Simulado: R$ 115.00 (Parabéns! Com a redução, você tem saldo positivo.)

---

### 💡 Análise da Simulação

**Resumo da Situação:** Ao reduzir 10% nas suas despesas variáveis, o saldo do seu orçamento foi de `R$ {saldo_final_simulado:.2f}`.

**Diagnóstico Financeiro:** Se antes havia um pequeno déficit, essa simulação mostra que uma ação focada nas despesas variáveis pode rapidamente transformar a situação. Um saldo positivo, mesmo que pequeno, é um grande passo para a sua saúde financeira.

**Recomendações Práticas:**
1.  **Priorize:** Se o saldo se tornou positivo, ótimo! Isso mostra o poder de pequenas reduções. Continue explorando onde mais pode economizar.
2.  **Se ainda negativo:** Se o saldo ainda está negativo, mesmo com a redução de 10%, pode ser necessário revisar as despesas variáveis de forma mais aprofundada ou buscar formas de aumentar a renda.

**Exemplo Aplicado:** A redução de 10% no 'Lazer/Entretenimento' pode significar escolher um programa mais barato uma vez ao mês ou procurar alternativas gratuitas.

**Plano de Ação Passo a Passo:**
1.  **Revisão Real:** Olhe para cada item das suas despesas variáveis e identifique quais 10% você pode realmente cortar.
2.  **Implementar:** Comece a aplicar essas reduções no seu dia a dia.
3.  **Monitorar:** Acompanhe seus gastos para garantir que está cumprindo as metas.

**Próximas Ações Recomendadas:**
*   **Meta Financeira Prática para os Próximos 7 Dias:** Escolha *duas* categorias de despesas variáveis onde você sente que pode aplicar uma redução real de 10% e monitore seus gastos nelas rigorosamente.
*   **Dica Educativa Adicional:** Pequenas economias, quando consistentes, se transformam em grandes resultados. O hábito de revisar seus gastos regularmente é mais importante do que cortes drásticos e insustentáveis.

### 📊 Automatizando o Registro Diário de Gastos

Para automatizar o registro, vamos usar a biblioteca `pandas`. Ela nos permite criar uma estrutura de dados (DataFrame) similar a uma planilha, onde podemos adicionar e organizar nossos gastos diários de forma eficiente.

In [6]:
import pandas as pd
from datetime import datetime

# Vamos criar um DataFrame vazio para armazenar os gastos diários.
# Se você já tiver um arquivo CSV com gastos anteriores, pode carregá-lo aqui:
# df_gastos_diarios = pd.read_csv('meus_gastos.csv')

# Para começar do zero, criamos um DataFrame com as colunas necessárias:
df_gastos_diarios = pd.DataFrame(columns=['Data', 'Categoria', 'Valor', 'Descrição'])

print("DataFrame de gastos diários criado:")
display(df_gastos_diarios.head())

DataFrame de gastos diários criado:

Empty DataFrame
Columns: [Data, Categoria, Valor, Descrição]
Index: []

#### Função para Adicionar um Gasto

Esta função facilitará o registro de cada nova despesa no seu `DataFrame`.

In [7]:
def adicionar_gasto(df, data, categoria, valor, descricao=''):
    # Garante que a data seja um objeto datetime
    if isinstance(data, str):
        data = datetime.strptime(data, '%Y-%m-%d')

    novo_gasto = pd.DataFrame([{'Data': data, 'Categoria': categoria, 'Valor': valor, 'Descrição': descricao}])
    df = pd.concat([df, novo_gasto], ignore_index=True)
    return df

print("Função 'adicionar_gasto' definida.")

Função 'adicionar_gasto' definida.

#### Registrando Alguns Gastos de Exemplo

Vamos registrar alguns gastos para demonstrar como funciona. Você pode repetir esta célula ou chamar a função `adicionar_gasto` quantas vezes precisar para registrar suas despesas.

In [8]:
# Adicione seus gastos aqui
df_gastos_diarios = adicionar_gasto(df_gastos_diarios, '2024-07-01', 'Alimentação (Mercado)', 150.00, 'Compras da semana')
df_gastos_diarios = adicionar_gasto(df_gastos_diarios, '2024-07-02', 'Transporte (Uber)', 25.50, 'Ida ao trabalho')
df_gastos_diarios = adicionar_gasto(df_gastos_diarios, '2024-07-03', 'Alimentação (Restaurantes/Delivery)', 45.00, 'Almoço com colegas')
df_gastos_diarios = adicionar_gasto(df_gastos_diarios, '2024-07-03', 'Lazer/Entretenimento', 60.00, 'Cinema')
df_gastos_diarios = adicionar_gasto(df_gastos_diarios, '2024-07-04', 'Alimentação (Mercado)', 80.00, 'Compras complementares')
df_gastos_diarios = adicionar_gasto(df_gastos_diarios, '2024-07-05', 'Outras Despesas Variáveis', 35.00, 'Presente')

print("Gastos adicionados:")
display(df_gastos_diarios)

Gastos adicionados:

/tmp/ipykernel_44126/1761366769.py:7: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, novo_gasto], ignore_index=True)

,Data,Categoria,Valor,Descrição
0,2024-07-01,Alimentação (Mercado),150.0,Compras da semana
1,2024-07-02,Transporte (Uber),25.5,Ida ao trabalho
2,2024-07-03,Alimentação (Restaurantes/Delivery),45.0,Almoço com colegas
3,2024-07-03,Lazer/Entretenimento,60.0,Cinema
4,2024-07-04,Alimentação (Mercado),80.0,Compras complementares
5,2024-07-05,Outras Despesas Variáveis,35.0,Presente

#### Agregando Gastos Diários para o Orçamento

Agora, vamos somar esses gastos por categoria para ter um panorama das suas despesas variáveis reais, que serão usadas no cálculo final do orçamento.

In [9]:
# Agrupar os gastos diários por categoria para obter as despesas variáveis reais
despesas_variaveis_reais = df_gastos_diarios.groupby('Categoria')['Valor'].sum().to_dict()

print("\n--- Despesas Variáveis Reais (do registro diário) ---")
for categoria, valor in despesas_variaveis_reais.items():
    print(f"{categoria}: R$ {valor:.2f}")

total_despesas_variaveis_reais = sum(despesas_variaveis_reais.values())
print(f"\nTotal de Despesas Variáveis Reais: R$ {total_despesas_variaveis_reais:.2f}")

--- Despesas Variáveis Reais (do registro diário) ---
Alimentação (Mercado): R$ 230.00
Alimentação (Restaurantes/Delivery): R$ 45.00
Lazer/Entretenimento: R$ 60.00
Outras Despesas Variáveis: R$ 35.00
Transporte (Uber): R$ 25.50

Total de Despesas Variáveis Reais: R$ 395.50

#### Recalculando o Orçamento com Gastos Reais

Vamos recalcular o resumo do seu orçamento usando as despesas variáveis **reais** que você registrou, em vez das estimadas.

In [10]:
# Recalcular o orçamento com as despesas variáveis reais
total_despesas_reais = total_despesas_fixas + total_despesas_variaveis_reais
saldo_final_recalculado = total_receitas - total_despesas_reais

print("\n--- Resumo do Orçamento Mensal (com Gastos Reais) ---")
print(f"Total de Receitas: R$ {total_receitas:.2f}")
print(f"Total de Despesas Fixas: R$ {total_despesas_fixas:.2f}")
print(f"Total de Despesas Variáveis Reais: R$ {total_despesas_variaveis_reais:.2f}")
print(f"Total Geral de Despesas Reais: R$ {total_despesas_reais:.2f}")

print("----------------------------------------------------")
if saldo_final_recalculado > 0:
    print(f"🎉 Saldo Final (Real): R$ {saldo_final_recalculado:.2f} (Parabéns! Você está com saldo positivo.)")
elif saldo_final_recalculado < 0:
    print(f"💸 Saldo Final (Real): R$ {saldo_final_recalculado:.2f} (Atenção! Você está com saldo negativo. Hora de revisar os gastos.)")
else:
    print(f"⚖️ Saldo Final (Real): R$ {saldo_final_recalculado:.2f} (Seu orçamento está equilibrado.)")

--- Resumo do Orçamento Mensal (com Gastos Reais) ---
Total de Receitas: R$ 3750.00
Total de Despesas Fixas: R$ 2420.00
Total de Despesas Variáveis Reais: R$ 395.50
Total Geral de Despesas Reais: R$ 2815.50
----------------------------------------------------
🎉 Saldo Final (Real): R$ 934.50 (Parabéns! Você está com saldo positivo.)

---

### 🌟 Próximos Passos e Recomendações para o Registro Diário

**Resumo da Situação:** Você agora tem um sistema em Python para registrar seus gastos diários e ver como eles afetam seu orçamento em tempo real.

**Diagnóstico Financeiro:** O novo saldo final, baseado em gastos reais, é a sua verdade financeira. Compará-lo com seu orçamento estimado é crucial para identificar desvios.

**Recomendações Práticas:**
1.  **Consistência:** O segredo do sucesso é registrar *todos* os gastos, por menores que sejam.
2.  **Categorização:** Seja o mais específico possível nas categorias para entender exatamente onde seu dinheiro está indo.
3.  **Revisão Periódica:** Ao final da semana ou do mês, revise seus `df_gastos_diarios` e o `saldo_final_recalculado`.

**Exemplo Aplicado:** Se você registrar R$ 10,00 de café todos os dias e perceber que isso impacta significativamente sua categoria 'Alimentação (Restaurantes/Delivery)', pode ser um gatilho para levar café de casa em alguns dias.

**Plano de Ação Passo a Passo:**
1.  **Execute as células acima:** Crie seu sistema de registro e adicione alguns gastos de exemplo.
2.  **Personalize categorias:** Adapte as categorias de gastos para as que fazem sentido para você.
3.  **Incorpore ao dia a dia:** Faça do registro de gastos um hábito. Pode ser à noite, antes de dormir, ou logo após cada despesa.

**Próximas Ações Recomendadas:**
*   **Meta Financeira Prática para os Próximos 7 Dias:** Registre *todos* os seus gastos diários pelos próximos 7 dias utilizando a função `adicionar_gasto`. Ao final, execute a célula de recalcular o orçamento e compare com sua estimativa inicial.
*   **Dica Educativa Adicional:** A consciência é o primeiro passo para a mudança. Ao registrar seus gastos, você se torna um detetive do seu próprio dinheiro, descobrindo para onde ele realmente está indo e onde você tem o poder de redirecioná-lo para seus objetivos.

Se quiser, posso te ajudar a salvar esses gastos em um arquivo (como CSV) para que você não os perca ao fechar o notebook! O que você acha?

### 💾 Salvando o Registro de Gastos em CSV

É fundamental salvar seus dados de gastos para que você não os perca ao fechar o notebook e possa acessá-los e atualizá-los em futuras sessões. Usaremos a função `to_csv()` do pandas para isso.

In [11]:
nome_arquivo_csv = 'meus_gastos_diarios.csv'
df_gastos_diarios.to_csv(nome_arquivo_csv, index=False)

print(f"DataFrame de gastos diários salvo em '{nome_arquivo_csv}' com sucesso!")

DataFrame de gastos diários salvo em 'meus_gastos_diarios.csv' com sucesso!

---

### ✅ Próximos Passos e Recomendações (Salvamento de Dados)

**Resumo da Situação:** Você agora sabe como salvar seu registro de gastos diários em um arquivo CSV, garantindo a persistência dos seus dados.

**Diagnóstico Financeiro:** A capacidade de salvar seus dados é um pilar importante para um controle financeiro robusto, permitindo que você construa um histórico detalhado e faça análises de longo prazo.

**Recomendações Práticas:**
1.  **Salve Regularmente:** Acostume-se a executar a célula de salvamento após cada nova entrada de gasto ou ao final de cada sessão de registro.
2.  **Carregar Dados:** Para continuar de onde parou em uma próxima sessão, você pode usar `df_gastos_diarios = pd.read_csv('meus_gastos_diarios.csv')` na célula onde o DataFrame é inicializado.
3.  **Backup:** Considere fazer backups periódicos desse arquivo CSV em um local seguro (nuvem, outro drive).

**Exemplo Aplicado:** Se você registrar gastos por uma semana e esquecer de salvar, todos os dados dessa semana seriam perdidos. Ao salvar regularmente, você protege esse valioso histórico.

**Plano de Ação Passo a Passo:**
1.  **Execute a célula de salvamento:** Garanta que seus gastos de exemplo já estão salvos.
2.  **Teste o Carregamento:** Você pode reiniciar o kernel e tentar carregar o arquivo CSV para ver se funciona corretamente.

**Próximas Ações Recomendadas:**
*   **Meta Financeira Prática para os Próximos 7 Dias:** Além de registrar seus gastos diários, crie o hábito de salvar o arquivo CSV ao final de cada dia. A consistência no registro e salvamento é fundamental.
*   **Dica Educativa Adicional:** A organização dos dados é tão importante quanto a coleta. Um histórico de gastos bem organizado é um tesouro de informações que te permite tomar decisões financeiras cada vez mais inteligentes.

O que achou? Gostaria de adicionar a funcionalidade de carregar o arquivo CSV na inicialização do DataFrame, ou talvez explorar como visualizar esses dados de gastos de forma gráfica?

### 📈 Análise de Gastos por Categoria

Vamos agora agrupar e somar os valores do `df_gastos_diarios` por categoria para ter uma visão consolidada de quanto foi gasto em cada uma. Isso é fundamental para identificar seus principais padrões de consumo.

In [12]:
gastos_por_categoria = df_gastos_diarios.groupby('Categoria')['Valor'].sum().sort_values(ascending=False)

print("\n--- Total de Gastos por Categoria ---")
display(gastos_por_categoria)

total_geral_gastos_registrados = gastos_por_categoria.sum()
print(f"\nTotal Geral de Gastos Registrados: R$ {total_geral_gastos_registrados:.2f}")

--- Total de Gastos por Categoria ---

Categoria
Alimentação (Mercado)                  230.0
Lazer/Entretenimento                    60.0
Alimentação (Restaurantes/Delivery)     45.0
Outras Despesas Variáveis               35.0
Transporte (Uber)                       25.5
Name: Valor, dtype: float64

Total Geral de Gastos Registrados: R$ 395.50

---

### 🔍 Análise e Recomendações dos Gastos por Categoria

**Resumo da Situação:** Você acabou de visualizar um resumo claro de quanto gastou em cada categoria. Isso é um raio-x valioso da sua vida financeira.

**Diagnóstico Financeiro:** As categorias com os maiores valores são seus 'vilões' ou 'heróis' financeiros. Elas representam as maiores oportunidades para otimização ou, se forem gastos essenciais e controlados, mostram que você está alinhado com suas prioridades.

**Recomendações Práticas:**
1.  **Top Gastos:** Olhe para as 2 ou 3 categorias com os maiores gastos. Pergunte-se: "Eu posso reduzir este valor sem comprometer minha qualidade de vida?" ou "Este gasto está alinhado com meus valores e objetivos?".
2.  **Oportunidades de Corte:** Se houver categorias onde você percebe que gastou mais do que gostaria, é ali que a ação deve começar.
3.  **Comparações:** Compare esses totais com os limites que você havia estabelecido (ou com a sua expectativa).

**Exemplo Aplicado:** Se 'Alimentação (Mercado)' e 'Alimentação (Restaurantes/Delivery)' forem as categorias mais altas, você pode planejar melhor suas refeições da semana, fazer listas de compras e levar marmita para o trabalho para reduzir o gasto com restaurantes.

**Plano de Ação Passo a Passo:**
1.  **Identifique 1-2 Categorias-Alvo:** Escolha as categorias onde você mais quer ou precisa agir.
2.  **Defina uma Meta de Redução:** Para cada categoria-alvo, defina um valor realista para reduzir no próximo mês (ex: "Reduzir R$ 50,00 em Lazer/Entretenimento").
3.  **Brainstorm de Ações:** Pense em ações concretas que você pode fazer para alcançar essa meta (ex: "Em vez de sair para jantar duas vezes, vou cozinhar em casa uma vez e sair na outra").

**Próximas Ações Recomendadas:**
*   **Meta Financeira Prática para os Próximos 7 Dias:** Analise a lista `gastos_por_categoria` e escolha uma categoria que represente uma oportunidade de economia. Pense em uma ação concreta para reduzir essa despesa em 10% durante a próxima semana e comprometa-se a implementá-la.
*   **Dica Educativa Adicional:** A 'regra dos 30 dias' pode ser útil para compras não essenciais. Se você deseja algo, espere 30 dias antes de comprar. Muitas vezes, o desejo passa e você economiza dinheiro. Se ainda quiser, compre com consciência!